# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd-components
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "10"
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/kubernickels/test-repo.git
#     path: registry
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/kubernickels/test-repo.git
    path: registry/argocd-overlay
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2